name       : python-pynacl
version    : 1.3.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz : 0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c
license    : Apache-2.0
component  : programming.python
summary    : Python binding to the Networking and Cryptography (NaCl) library
description: |
    Python binding to the Networking and Cryptography (NaCl) library
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(python3)
    - python-cffi
rundeps    :
    - libsodium
    - python-cffi
    - python-six
setup      : |
    export SODIUM_INSTALL=system
    %python3_setup
install    : |
    %python3_install
