name       : python-pynacl
version    : 1.2.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/08/19/cf56e60efd122fa6d2228118a9b345455b13ffe16a14be81d025b03b261f/PyNaCl-1.2.1.tar.gz : e0d38fa0a75f65f556fb912f2c6790d1fa29b7dd27a1d9cc5591b281321eaaa9
license    : Apache-2.0
component  : programming.python
summary    : Python binding to the Networking and Cryptography (NaCl) library
description: |
    Python binding to the Networking and Cryptography (NaCl) library
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(python3)
    - python-cffi
rundeps  :
    - libsodium
    - python-cffi
    - python-six
setup      : |
    export SODIUM_INSTALL=system
    %python3_setup
install    : |
    %python3_install
