name       : python-pynacl
version    : 1.4.0
release    : 4
source     :
    - https://pypi.io/packages/source/P/PyNaCl/PyNaCl-1.4.0.tar.gz : 54e9a2c849c742006516ad56a88f5c74bf2ce92c9f67435187c3c5953b346505
license    : Apache-2.0
component  : programming.python
summary    : Python binding to the Networking and Cryptography (NaCl) library
description: |
    Python binding to the Networking and Cryptography (NaCl) library
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(python3)
    - python-cffi
    - python-wheel
rundeps    :
    - libsodium
    - python-cffi
    - python-six
setup      : |
    export SODIUM_INSTALL=system
    %python3_setup
install    : |
    %python3_install
