name       : python-pynacl
version    : 1.5.0
release    : 7
source     :
    - https://pypi.io/packages/source/P/PyNaCl/PyNaCl-1.5.0.tar.gz : 8ac7448f09ab85811607bdd21ec2464495ac8b7c66d146bf545b0f08fb9220ba
license    : Apache-2.0
component  : programming.python
summary    : Python binding to the Networking and Cryptography (NaCl) library
description: |
    PyNaCl is a Python binding to libsodium, which is a fork of the Networking and Cryptography library. These libraries have a stated goal of improving usability, security and speed.
builddeps  :
    - pkgconfig(libsodium)
    - pkgconfig(python3)
    - python-cffi
    - python-wheel
rundeps    :
    - libsodium
    - python-cffi
    - python-six
setup      : |
    export SODIUM_INSTALL=system
    %python3_setup
install    : |
    %python3_install
